name: Chore Template
description: 기타 변경 사항
title: "[Chore] Title"
labels: ["chore"]

body:
  - type: textarea
    id: chore-description
    attributes:
      label: 설명
      description: 기타 변경할 사항에 대한 설명을 적어주세요.
      placeholder: ex. json 파일 교체
    validations:
      required: true
